### ISSUE TITLE
Problem converting Joplin to textbundle (attach files with spaces)

### ISSUE THREAD

**Issue by jesusdeveloper** [devinhurry/markdown-to-textbundle-for-bear#1]
Hello!

First of all, your script is very useful!!!! Thank you very much for developing it!
I want to tell you about a problem I have when I export a Joplin note (markdown + Front Matter) and it contains a file that has name with spaces then the images are not exported correctly.

For example, when I use Joplin and I put in the note an image that has name with spaces ("screen shot" or "document pdf") Joplin stores it in a folder called "_resources" and stores it:
```
/_resources/screen shot.jpg
/_resources/document pdf.pdf
```

I export this note as markdown and Front Matter. This note contains image and document links but in the spaces, Joplin puts "%20". In the markdown you see it like this:

```
![screen shot.png](../_resources/screen%20shot.png)
[document pdf.pdf](../_resources/document%20pdf.pdf)
```

Note: (you can see that instead of a space, Joplin exporting adds %20 to the spaces).

Then, I use your script. Your script generates the textbundle file correctly. Then to see the markdown I right click on the textbundle file and press "Show package contents" and the generated markdown is:

-----------------------------------------------------------
```
---
title: Title exportation example
updated: 2023-03-25 18:32:49Z
created: 2023-03-25 18:24:41Z
latitude: 40.44752720
longitude: -3.80741520
altitude: 0.0000
---

Hello!

The following line is an image imported into Joplin and the image file name has spaces (screen shot):

![screen shot.png](assets/screen%2520shot.png)

The following line is a pdf file imported into Joplin and has spaces (document pdf):

[document pdf.pdf](../_resources/document%20pdf.pdf)

```
-----------------------------------------------------------

But there are two problems:

1. your script adds in addition "25" between the symbol "%" and the number 20 as you can see.
2. Your script does not change the path correctly. The attachments are put in a folder called assets but the markdown has in its path the default Joplin folder: _resources. 

So Bear doesn't find the path to the image and it doesn't find the path to the attachment either.

Do you think you could fix this?

It would be ideal!!!! I am using the Bear 2 beta.

Thank you very much for reading me and thank you for your script!!!

# EDIT: Possible solutions

Hello!

I think I have discovered the solution (although the script would have to be modified) for images and attachments when they have spaces in their name in Joplin.

## For images

When I export in Joplin a note containing an image with space, in the markdown Joplin adds %20 for each space of the attached image and this is correct because if you read it with any markdown reader it looks correctly, that is, the markdown exported by Joplin looks like this:

`![screen shot.png](../_resources/screen%20shot.png)`
(Add a %20 in the space between screen and shot)

Now we use your script and convert that markdown + Front Matter to textbundle. Inside assets we find correctly the image screen shot.png. But the result of the markdown in the textbundle with your script is:

`![screen shot.png](assets/screen%2520shot.png)
`
If we import the textbundle in Bear, it does not recognize it, but to make it work, we have to make modifications to that line:
-Remove the inner [ ], i.e. 
`![screen shot.png] is: ![]`
-Modify the path in parenthesis the path "assets/" and eliminate the number 25.
The correct line would look like this:

`![](screen%20shot.png)`

And now the image is visible in Bear 2 :)

## For attachments

When I export in Joplin a note that contains an attached file (for example a pdf file) with space in its name, in the markdown Joplin adds %20 for each space of the attached file and this is correct because if you read it with any markdown reader it looks correctly, that is, the markdown exported by Joplin looks like this:

`[document pdf.pdf](../_resources/document%20pdf.pdf)`
(Add a %20 in the space between document and pdf)

Now we use your script and convert that markdown + Front Matter to textbundle. 
Problem to fix: Inside the assets folder is NOT the attachment "document pdf.pdf". 
INVESTIGATE: We need to investigate why the script does not import the Joplin pdf files into the textbundle assets folder.
To go ahead, let's imagine that I have added the document pdf.pdf file in the assets folder. The result of the markdown in the textbundle with your script is:

`[document pdf.pdf](../_resources/document%20pdf.pdf)`

From that line I think the script does nothing. But that line should be transformed to make the document look good in Bear 2 like this:

`[document%20pdf.pdf](document%20pdf.pdf)<!-- {"embed": "true", "preview": "true"} -->`

And then the file looks correctly in Bear 2.

Hopefully you have some time to help me and the reddit group to move us to Bear 2.

Thanks for reading me!

**Comment by devinhurry** [comment]
@jesusdeveloper Thank you for writing so long, I will have a look at it.

**Comment by devinhurry** [comment]
The latest update fix the issue and add some other useful things too. Check it out and report to me if any other issues found.

**Comment by jesusdeveloper** [comment]
> The latest update fix the issue and add some other useful things too. Check it out and report to me if any other issues found.

Hello @devinhurry 

I want to thank you, I have been able to transfer all my Joplin notes to Bear 2 excellently.
I am very grateful, you are amazing, thank you for taking your time, you are a great person!!!!

**Comment by devinhurry** [comment]
> > The latest update fix the issue and add some other useful things too. Check it out and report to me if any other issues found.
> 
> Hello @devinhurry
> 
> I want to thank you, I have been able to transfer all my Joplin notes to Bear 2 excellently. I am very grateful, you are amazing, thank you for taking your time, you are a great person!!!!

@jesusdeveloper Glad to hear that. I just decided move away fro m Bear 2 because they just announce the new price plan, which seems not worth it considering all the functionality it has.

**Comment by jesusdeveloper** [comment]
> > > The latest update fix the issue and add some other useful things too. Check it out and report to me if any other issues found.
> > 
> > 
> > Hello @devinhurry
> > I want to thank you, I have been able to transfer all my Joplin notes to Bear 2 excellently. I am very grateful, you are amazing, thank you for taking your time, you are a great person!!!!
> 
> @jesusdeveloper Glad to hear that. I just decided move away fro m Bear 2 because they just announce the new price plan, which seems not worth it considering all the functionality it has.

That's right! I was really looking forward to the option of integrating the panda editor in Bear and it's finally ready. I think it's the only markdown editor that has that functionality, for me, it's amazing.
And you were able to help me pass my Joplin notes!!!
Thanks again!!!
